//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class agency
    {
        public agency()
        {
            this.routes = new HashSet<route>();
        }
    
        public int agency_id { get; set; }
        public string agency_phone { get; set; }
        public string agency_url { get; set; }
        public string agency_name { get; set; }
        public string agency_timezone { get; set; }
        public string agency_lang { get; set; }
        public string agency_fare_url { get; set; }
    
        public virtual ICollection<route> routes { get; set; }
    }
}
