//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class route
    {
        public route()
        {
            this.buses = new HashSet<bus>();
            this.trips = new HashSet<trip>();
        }
    
        public int route_id { get; set; }
        public Nullable<int> agency_id { get; set; }
        public string route_short_name { get; set; }
        public string route_long_name { get; set; }
        public string route_desc { get; set; }
        public Nullable<byte> route_type { get; set; }
        public string route_url { get; set; }
        public string route_color { get; set; }
        public string route_text_color { get; set; }
    
        public virtual agency agency { get; set; }
        public virtual ICollection<bus> buses { get; set; }
        public virtual ICollection<trip> trips { get; set; }
    }
}
