//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class stop_times
    {
        public int trip_id { get; set; }
        public Nullable<System.TimeSpan> arrival_time { get; set; }
        public Nullable<System.TimeSpan> departure_time { get; set; }
        public int stop_id { get; set; }
        public Nullable<int> stop_sequence { get; set; }
        public string stop_headsign { get; set; }
        public Nullable<byte> pickup_type { get; set; }
        public Nullable<byte> drop_off_type { get; set; }
        public double shape_dist_traveled { get; set; }
    
        public virtual stop stop { get; set; }
        public virtual trip trip { get; set; }
    }
}
