//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class stop
    {
        public stop()
        {
            this.stop_times = new HashSet<stop_times>();
        }
    
        public int stop_id { get; set; }
        public string stop_code { get; set; }
        public string stop_name { get; set; }
        public string stop_desc { get; set; }
        public Nullable<decimal> stop_lat { get; set; }
        public Nullable<decimal> stop_lon { get; set; }
        public Nullable<int> zone_id { get; set; }
        public string stop_url { get; set; }
        public Nullable<bool> location_type { get; set; }
        public Nullable<bool> parent_station { get; set; }
        public string stop_timezone { get; set; }
        public Nullable<byte> wheelchair_boarding { get; set; }
    
        public virtual ICollection<stop_times> stop_times { get; set; }
    }
}
